/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutStartupRouteImport } from './routes/_layout/startup'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutServicesRouteImport } from './routes/_layout/services'
import { Route as LayoutProcessesRouteImport } from './routes/_layout/processes'
import { Route as LayoutDetailsRouteImport } from './routes/_layout/details'
import { Route as LayoutAppHistoryRouteImport } from './routes/_layout/app-history'
import { Route as LayoutPerformanceIndexRouteImport } from './routes/_layout/performance.index'
import { Route as LayoutPerformanceMetricIdRouteImport } from './routes/_layout/performance.$metricId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStartupRoute = LayoutStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesRoute = LayoutServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProcessesRoute = LayoutProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDetailsRoute = LayoutDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppHistoryRoute = LayoutAppHistoryRouteImport.update({
  id: '/app-history',
  path: '/app-history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPerformanceIndexRoute = LayoutPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPerformanceMetricIdRoute =
  LayoutPerformanceMetricIdRouteImport.update({
    id: '/performance/$metricId',
    path: '/performance/$metricId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-history': typeof LayoutAppHistoryRoute
  '/details': typeof LayoutDetailsRoute
  '/processes': typeof LayoutProcessesRoute
  '/services': typeof LayoutServicesRoute
  '/settings': typeof LayoutSettingsRoute
  '/startup': typeof LayoutStartupRoute
  '/users': typeof LayoutUsersRoute
  '/performance/$metricId': typeof LayoutPerformanceMetricIdRoute
  '/performance/': typeof LayoutPerformanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-history': typeof LayoutAppHistoryRoute
  '/details': typeof LayoutDetailsRoute
  '/processes': typeof LayoutProcessesRoute
  '/services': typeof LayoutServicesRoute
  '/settings': typeof LayoutSettingsRoute
  '/startup': typeof LayoutStartupRoute
  '/users': typeof LayoutUsersRoute
  '/performance/$metricId': typeof LayoutPerformanceMetricIdRoute
  '/performance': typeof LayoutPerformanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/app-history': typeof LayoutAppHistoryRoute
  '/_layout/details': typeof LayoutDetailsRoute
  '/_layout/processes': typeof LayoutProcessesRoute
  '/_layout/services': typeof LayoutServicesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/startup': typeof LayoutStartupRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/performance/$metricId': typeof LayoutPerformanceMetricIdRoute
  '/_layout/performance/': typeof LayoutPerformanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-history'
    | '/details'
    | '/processes'
    | '/services'
    | '/settings'
    | '/startup'
    | '/users'
    | '/performance/$metricId'
    | '/performance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-history'
    | '/details'
    | '/processes'
    | '/services'
    | '/settings'
    | '/startup'
    | '/users'
    | '/performance/$metricId'
    | '/performance'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/app-history'
    | '/_layout/details'
    | '/_layout/processes'
    | '/_layout/services'
    | '/_layout/settings'
    | '/_layout/startup'
    | '/_layout/users'
    | '/_layout/performance/$metricId'
    | '/_layout/performance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/startup': {
      id: '/_layout/startup'
      path: '/startup'
      fullPath: '/startup'
      preLoaderRoute: typeof LayoutStartupRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services': {
      id: '/_layout/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof LayoutServicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/processes': {
      id: '/_layout/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof LayoutProcessesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/details': {
      id: '/_layout/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof LayoutDetailsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app-history': {
      id: '/_layout/app-history'
      path: '/app-history'
      fullPath: '/app-history'
      preLoaderRoute: typeof LayoutAppHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/performance/': {
      id: '/_layout/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof LayoutPerformanceIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/performance/$metricId': {
      id: '/_layout/performance/$metricId'
      path: '/performance/$metricId'
      fullPath: '/performance/$metricId'
      preLoaderRoute: typeof LayoutPerformanceMetricIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAppHistoryRoute: typeof LayoutAppHistoryRoute
  LayoutDetailsRoute: typeof LayoutDetailsRoute
  LayoutProcessesRoute: typeof LayoutProcessesRoute
  LayoutServicesRoute: typeof LayoutServicesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStartupRoute: typeof LayoutStartupRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutPerformanceMetricIdRoute: typeof LayoutPerformanceMetricIdRoute
  LayoutPerformanceIndexRoute: typeof LayoutPerformanceIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAppHistoryRoute: LayoutAppHistoryRoute,
  LayoutDetailsRoute: LayoutDetailsRoute,
  LayoutProcessesRoute: LayoutProcessesRoute,
  LayoutServicesRoute: LayoutServicesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStartupRoute: LayoutStartupRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutPerformanceMetricIdRoute: LayoutPerformanceMetricIdRoute,
  LayoutPerformanceIndexRoute: LayoutPerformanceIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
